### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by drag00n** [fnichol/chef-rvm#291]
I was wondering if there was a reason that this cookbook does not have a license. It seems like Apache 2 is the most common license for most Chef cookbooks.

**Comment by martinisoft** [comment]
@drag00n while a LICENSE file does not exist for this project (yet) there is notice [given in the README](https://github.com/fnichol/chef-rvm#-license-and-author)

**Comment by drag00n** [comment]
Totally missed that. Thanks @martinisoft
