### ISSUE TITLE
gemsets not being created?

### ISSUE THREAD

**Issue by chhsiung** [fnichol/chef-rvm#296]
I'm having trouble getting global gems installed using this recipe. My attributes are:

```
default['rvm']['user_installs'] = [
  {
    'user' => 'jenkins',
    'home' => '/var/lib/jenkins',
    'default_ruby' => '1.9.3-p392',
    'rubies' => ['1.9.3-p392', '2.1.2'],
    'global_gems' => [
      { 'name' => 'bundler' },
      { 'name' => 'fpm' }
    ],
  }
]
```

I get the following errors:
```
Error executing action `install` on resource 'rvm_gem[bundler]'
STDERR: Gemset 'global' does not exist, 'rvm ruby-1.9.3-p392 do rvm gemset create global' first, or append '--create'.
```

When I ssh onto my box, I see that no gemset has been created, but if I manually create the gemset, everything appears fine (my global gems are available).  In my debugging, I attempted to use the recipe to add the gemset with `rvm_gemset 'ruby-1.9.3-p392@global'` and ran into the following errors (that I assume may be why the recipe is not creating the global gemset by default as it claims it should:

```
Error executing action `create` on resource 'rvm_gemset[ruby-1.9.3-p392@global]'
undefined method `chomp' for nil:NilClass
/tmp/kitchen/cache/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:77:in `canonical_ruby_string'       
/tmp/kitchen/cache/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:50:in `fetch'       
/tmp/kitchen/cache/cookbooks/rvm/libraries/chef_rvm_string_helpers.rb:55:in `normalize_ruby_string'       
/tmp/kitchen/cache/cookbooks/rvm/providers/gemset.rb:31:in `load_current_resource' 
```

Any idea why my global gems won't install?  Is it related at all to the fact that I can't seem to get the gemsets to create?

**Comment by chhsiung** [comment]
I found this https://github.com/fnichol/chef-rvm/issues/141 which seems to have a similar issue, but I am including a rvm recipe. I am including 'rvm::user'

**Comment by david-crowder** [comment]
I am also having this issue. Nothing has changed in my cookbook, but in vagrant the global gemset is no longer getting created.

**Comment by david-crowder** [comment]
Just noticed earlier in the run:
```
Failed to install rvm_ruby[ruby-1.9.3-p484]. Check logs in /log/ruby-1.9.3-p484
rvm_ruby[ruby-1.9.3-p484] build time was 2.3483851822 minutes.
```
Though it appears that ruby was installed just fine. Sifting through the logs now to see if there is any hint as to why the gemset didn't get created.

**Comment by david-crowder** [comment]
I tried recreating manually and ended up getting:
```
The requested url does not exist(22): 'http://production.cf.rubygems.org/rubygems/rubygems-2.2.3.tgz'
Checking fallback: ftp://production.cf.rubygems.org/rubygems/rubygems-2.2.3.tgz
Checking fallback: http://www.mirrorservice.org/sites/production.cf.rubygems.org/rubygems/rubygems-2.2.3.tgz
No fallback URL could be found, try increasing timeout with:

    echo "export rvm_max_time_flag=20" >> ~/.rvmrc

There has been an error while trying to fetch rubygems.
Halting the installation.
```
This left the box in the same state that it was in after the chef-client run. The correct ruby version was installed, but there was no global gemset.

**Comment by fxfilmxf** [comment]
+1 I'm having this issue as well

**Comment by WillBeebe** [comment]
I'm running into this too!

**Comment by chhsiung** [comment]
i think my problem may have actually been that rvm 1.25.26 (the version i was using) got pulled off of the rvm/releases here: https://github.com/wayneeseguin/rvm/releases

`Could not download 'https://github.com/wayneeseguin/rvm/releases/download/1.25.26/1.25.26.tar.gz.asc`

1.24.34 seems to be the latest version downloadable

**Comment by fxfilmxf** [comment]
Weird. I changed versions from 1.25.27 to 1.25.33 and that "fixed" it.

@chhsiung That file doesn't exist because there wasn't gpg security for versions prior to 1.25.34, hence the signature file doesn't exist for version 1.25.26.

**Comment by fxfilmxf** [comment]
@chhsiung Thanks so much btw for your comment about changing the rvm version!

**Comment by Zloy** [comment]
I am also having this issue. Nothing has changed in my cookbook, but in vagrant the global gemset is no longer getting created.

**Comment by david-crowder** [comment]
Just for completeness: I too have worked around this by upping the version of rvm I was installing. This required me to add the gpg stuff to get it to work, but I am not running into the error anymore. It doesn't look like it is an actual issue with the cookbook, but with rvm/rubygems.

**Comment by Zloy** [comment]
I could not work around by upping the version, but I continue applying recipies by executing in guest console `rvm use ruby-2.0.0-p353@global --create`

**Comment by chhsiung** [comment]
I am now on 1.25.33 and it works for me.  Going to close this issue.

**Comment by CharlieC3** [comment]
@chhsiung, can you please tell me how you specified the RVM version? I'm using the `rvm::system` recipe in my cookbook. Should this be working?
`node.set["rvm"]["installer_url"] = "https://github.com/wayneeseguin/rvm/archive/1.25.33.tar.gz"`

**Comment by CharlieC3** [comment]
@chhsiung or perhaps 
`node.set["rvm"]["installer_flags"] = "--version 1.25.33"`?
Neither of these seem to be working for me.

**Comment by jblaine** [comment]
@CharlieC3 Only a lurker here, but no, the URL needs to point to a version of the 'rvm-installer' script. You can find the raw version here for download to your intranet, etc. https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer

**Comment by Zloy** [comment]
Ok, I ended up with adding `rvm_gemset_create_on_use_flag` parameter to rvm options:

    "rvm": {
      "installer_url": "https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer",
      "branch": "none",
      "version": "1.25.28",
      "rvmrc": {
        "rvm_gemset_create_on_use_flag": 1
      },
      "user_installs": [{
        "user": "vagrant",
        "default_ruby": "ruby-2.0.0-p353@global"
      }]
